using System;
using System.Collections.Generic;
using System.Linq;
using HarmonyLib;
using SteamManagerRuntime;
using SteamManagerProtocol;
using UnityEngine;

namespace SteamManagerRuntimeTests
{
    public static partial class Entry
    {
        static void ExtendedChecks(Player p)
        {
            Bridge.Reset();Check(Bridge.Features.Count==54&&Bridge.Features.All(x=>x.Error==null),"All 54 features register without hook errors");
            bool god=p.InGodMode(),ghost=p.InGhostMode();Set(1,true);Check(p.InGodMode(),"God flag enabled");Set(1,false);Check(p.InGodMode()==god,"God flag restored");Set(5,true);Check(p.InGhostMode(),"Ghost flag enabled");Set(5,false);Check(p.InGhostMode()==ghost,"Ghost flag restored");
            foreach(int id in new[]{10,11,12}){string method=id==10?"ModifyHealthRegen":id==11?"ModifyStaminaRegen":"ModifyEitrRegen";var fn=AccessTools.Method(typeof(SEMan),method);object[] a={1f};fn.Invoke(p.GetSEMan(),a);float baseline=(float)a[0];Set(id,true,3);a=new object[]{1f};fn.Invoke(p.GetSEMan(),a);Near((float)a[0],baseline*3,"Regeneration hook "+id+" multiplies actual modifier");Set(id,false,1);}
            Field(p,"m_stamina",50);Set(13,true,0.5f);p.UseStamina(10);Near(p.GetStamina(),45,"Half stamina cost spends five for ten");Check(p.HaveStamina(60),"Stamina affordability uses modified cost");Set(13,false,1);
            Field(p,"m_eitr",50);Set(14,true,0.5f);p.UseEitr(10);Near(p.GetEitr(),45,"Half Eitr cost spends five for ten");Check(p.HaveEitr(60),"Eitr affordability uses modified cost");Set(14,false,1);
            float oldCooldown=p.m_guardianPowerCooldown;try{p.m_guardianPowerCooldown=20;Set(21,true,0.5f);AccessTools.Method(typeof(Player),"UpdateGuardianPower").Invoke(p,new object[]{1f});Near(p.m_guardianPowerCooldown,18,"Guardian cooldown progresses twice as fast");Set(21,true,0);Extended.Tick(p);Near(p.m_guardianPowerCooldown,0,"Zero cooldown clears timer");}finally{Set(21,false,1);p.m_guardianPowerCooldown=oldCooldown;}
            var effect=ScriptableObject.CreateInstance<StatusEffect>();try{effect.name="GP_Test";effect.m_character=p;effect.m_ttl=100;Set(22,true,2);effect.UpdateStatusEffect(1);Near((float)AccessTools.Field(typeof(StatusEffect),"m_time").GetValue(effect),0.5f,"Guardian duration halves timer progress");}finally{Set(22,false,1);UnityEngine.Object.Destroy(effect);}
            p.SetHealth(Math.Max(20,p.GetHealth()));var hit=new HitData();hit.m_damage.m_damage=4;float hp=p.GetHealth();p.ApplyDamage(hit,false,false);float normal=hp-p.GetHealth();hit=new HitData();hit.m_damage.m_damage=4;hp=p.GetHealth();Set(24,true,0.5f);p.ApplyDamage(hit,false,false);Near(hp-p.GetHealth(),normal*0.5f,"Received damage scales actual health loss");Set(24,false,1);
            var objectHit=new HitData();objectHit.SetAttacker(p);objectHit.m_damage.m_chop=2;objectHit.m_damage.m_pickaxe=3;Set(26,true,4);Extended.ObjectDamage(null,objectHit);Near(objectHit.m_damage.m_chop,8,"Chopping prefix multiplies tool damage");Near(objectHit.m_damage.m_pickaxe,12,"Mining uses shared gathering multiplier");Set(53,true,2);objectHit.m_damage.m_chop=2;objectHit.m_damage.m_pickaxe=3;Extended.ObjectDamage(null,objectHit);Near(objectHit.m_damage.m_pickaxe,6,"Independent mining overrides shared multiplier");Set(27,true);Extended.ObjectDamage(null,objectHit);Check(objectHit.m_damage.m_chop>=10000000&&objectHit.m_toolTier==short.MaxValue,"One-hit object prefix raises damage and tool tier");Set(27,false);Set(26,false,1);Set(53,false,1);
            var piecePrefab=ZNetScene.instance.GetPrefab("woodwall");var wear=piecePrefab.GetComponent<WearNTear>();Set(28,true);Check(!Extended.ObjectDamage(wear,objectHit),"Building protection blocks local object damage prefix");Set(28,false);Check(Extended.ObjectDamage(wear,objectHit),"Building damage prefix resumes when disabled");
            Set(38,true);Check(p.RequiredCraftingStation(null,1,true),"Building override bypasses required crafting station");var station=ObjectDB.instance.m_recipes.First(x=>x.m_craftingStation!=null).m_craftingStation;Check(station.CheckUsable(p,false),"Building override bypasses station roof usability");Set(38,false);
            var wood=Add(p,"Wood",2);var inv=Send(new Request{Command="inventory"});var carried=inv.Entries.Last(x=>x.Name==Localization.instance.Localize(wood.m_shared.m_name)&&x.Value==2);Send(new Request{Command="inventory-edit",Text=carried.Id,Quantity=3});Near(wood.m_stack,3,"Inventory token edits selected stack");bool rejected=false;try{Send(new Request{Command="inventory-edit",Text=carried.Id,Quantity=wood.m_shared.m_maxStackSize+1});}catch{rejected=true;}Check(rejected,"Inventory editor enforces game stack maximum");
            var torch=Add(p,"Torch",1);torch.m_durability=1;inv=Send(new Request{Command="inventory"});carried=inv.Entries.Last(x=>x.Name==Localization.instance.Localize(torch.m_shared.m_name));Send(new Request{Command="inventory-repair",Text=carried.Id});Near(torch.m_durability,torch.GetMaxDurability(),"Selected repair restores durability");
            var buffs=Send(new Request{Command="buffs"});Check(buffs.Entries.Count>0,"Buff browser reads installed status definitions");var buff=buffs.Entries.FirstOrDefault(x=>x.Name.Contains("[Rested]")&&!x.Unlocked);if(buff!=null){Send(new Request{Command="buff-add",Text=buff.Id,Value=123});Near(p.GetSEMan().GetStatusEffect(int.Parse(buff.Id)).m_ttl,123,"Buff application honors custom duration");Send(new Request{Command="buff-remove",Text=buff.Id});Check(p.GetSEMan().GetStatusEffect(int.Parse(buff.Id))==null,"Selected buff removed");}
            var levels=p.GetSkills().GetSkillList().ToDictionary(x=>x,x=>new[]{x.m_level,x.m_accumulator});try{foreach(int id in new[]{19,20}){Set(id,true);p.GetSkills().OnDeath();Check(levels.All(x=>Math.Abs(x.Key.m_level-x.Value[0])<0.001),"Skill death loss blocked by "+id);Set(id,false);}}finally{foreach(var pair in levels){pair.Key.m_level=pair.Value[0];pair.Key.m_accumulator=pair.Value[1];}}
            int items=p.GetInventory().GetAllItems().Count;Set(19,true);p.CreateTombStone();Check(p.GetInventory().GetAllItems().Count==items,"No death penalty skips inventory transfer to tombstone");Set(19,false);
            float run=p.m_runSpeed,swim=p.m_swimSpeed;Set(51,true,2);Near(p.m_runSpeed,run*2,"Independent sprint multiplier");Near(p.m_swimSpeed,swim,"Sprint leaves swim baseline");Set(52,true,3);Near(p.m_swimSpeed,swim*3,"Independent swim multiplier");Set(51,false,1);Set(52,false,1);
            var collider=p.GetComponent<CapsuleCollider>();var body=p.GetComponent<Rigidbody>();bool collision=collider.enabled,detect=body.detectCollisions,fly=p.IsDebugFlying();Set(40,true);Check(!collider.enabled&&!body.detectCollisions&&p.IsDebugFlying(),"Noclip enables flight and disables collisions");Set(40,false);Check(collider.enabled==collision&&body.detectCollisions==detect&&p.IsDebugFlying()==fly,"Noclip restores collision and flight state");
            bool hidden=Hud.instance.m_userHidden;Set(47,true);Check(Hud.instance.m_userHidden,"Hide HUD flag enabled");Set(47,false);Check(Hud.instance.m_userHidden==hidden,"HUD restored");float scale=Time.timeScale;Set(46,true,0.5f);Near(Time.timeScale,0.5f,"Game speed controls time scale");Set(46,false,1);Near(Time.timeScale,scale,"Game speed restores time scale");
            bool camera=GameCamera.InFreeFly();float fov=GameCamera.instance.m_fov;Set(48,true,80);Check(GameCamera.InFreeFly(),"Photo camera enters free fly");Near(GameCamera.instance.m_fov,80,"Photo camera FOV applied");Set(48,false,65);Check(GameCamera.InFreeFly()==camera,"Photo camera mode restored");Near(GameCamera.instance.m_fov,fov,"Camera FOV restored");
            bool clock=EnvMan.instance.m_debugTimeOfDay;Set(44,true);Check(EnvMan.instance.m_debugTimeOfDay,"Freeze daytime enables local visual clock");float time=EnvMan.instance.m_debugTime;Extended.Tick(p);Near(EnvMan.instance.m_debugTime,time,"Frozen visual time remains fixed");Set(44,false);Check(EnvMan.instance.m_debugTimeOfDay==clock,"Visual clock restored");
            var netTime=AccessTools.Field(typeof(ZNet),"m_netTime");double saved=(double)netTime.GetValue(ZNet.instance);try{Set(45,true,2);AccessTools.Method(typeof(ZNet),"UpdateNetTime").Invoke(ZNet.instance,new object[]{1f});Check(Math.Abs((double)netTime.GetValue(ZNet.instance)-saved-2)<0.02,"Single-player world clock multiplier changes elapsed time");}finally{Set(45,false,1);netTime.SetValue(ZNet.instance,saved);}
            string bookmark="__SteamManager_test_"+Guid.NewGuid().ToString("N");try{var locations=Send(new Request{Command="save-location",Text=bookmark});Check(locations.Entries.Any(x=>x.Id==bookmark),"Saved location created for current world");Check(Send(new Request{Command="locations"}).Entries.Any(x=>x.Id==bookmark),"Saved location loads from disk");}finally{Send(new Request{Command="delete-location",Text=bookmark});}Check(!Send(new Request{Command="locations"}).Entries.Any(x=>x.Id==bookmark),"Saved location deletion persists");
            Send(new Request{Command="profile",Settings=new List<Feature>{new Feature{Id=1,Enabled=true},new Feature{Id=6,Enabled=true,Value=3000}}});Check(p.InGodMode()&&p.GetMaxCarryWeight()==3000,"Profile applies multiple controls");rejected=false;try{Send(new Request{Command="profile",Settings=new List<Feature>{new Feature{Id=6,Value=-1}}});}catch{rejected=true;}Check(rejected&&p.InGodMode()&&p.GetMaxCarryWeight()==3000,"Invalid profile leaves active controls unchanged");Bridge.Reset();
            var achievements=Send(new Request{Command="achievements"});Check(achievements.Entries.Count>0,"Steam achievement browser returns account entries");rejected=false;try{Send(new Request{Command="unlock-achievement",Text=achievements.Entries[0].Id});}catch{rejected=true;}Check(rejected,"Achievement mutation requires explicit confirmation");rejected=false;try{Send(new Request{Command="unlock-achievement",Text="__invalid_steammanager_id__",Confirmed=true});}catch{rejected=true;}Check(rejected,"Unknown achievement rejected before Steam write");var after=Send(new Request{Command="achievements"});Check(achievements.Entries.All(x=>after.Entries.Single(y=>y.Id==x.Id).Unlocked==x.Unlocked),"Achievement validation leaves all unlock states unchanged");
        }
    }
}
